openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: "https://raw.githubusercontent.com/Luis-Felipe-dos-Santos-Pires/dredd_doc_open_api/staging/docs/Dredd.png"
  description:
    $ref: ./info-description.md

tags:
  - name: Rules
    description: Operations about rules.


servers:
  - url: 'http://172.19.203.28:57772/dredd/'

paths:
  '/users/{username}':
    $ref: 'paths/users_{username}.yaml'
  /echo:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
  "/rules":
    $ref: "paths/rule/rules.yaml"
  "/rule/{id}":
    $ref: "paths/rule/rule@{id}.yaml"
  "/rule/":
    $ref: "paths/rules/rule.yaml"


components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
